version: '3'
services:
  db:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"